import Head from 'next/head'
import useTranslation from "next-translate/useTranslation";
import { useRouter } from 'next/router'
import Navbar from '/components/layout/navbar';
import Hero from '../components/Hero';
import MallInNumbers from '../components/MallInNumbers';
import AboutAlamer from '../components/AboutAlamer';
import Department from '../components/Department';
import Partners from '../components/Partners';
import OurNew from '../components/OurNew';
import Newslatter from '../components/Newslatter';
import Subscribe from './api/subscribe';
import NewsletterSubscribe from '../components/NewsletterSubscribe';
import Footer from '../components/layout/footer';
export default function Home() {
  const { locale } = useRouter()
  const { t } = useTranslation("common");

  const currentDir = locale === 'ar' ? 'rtl' : 'ltr'
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <MallInNumbers />
      <AboutAlamer currentDir={currentDir} />
      <Department currentDir={currentDir} />
      <Partners currentDir={currentDir} />
      <OurNew currentDir={currentDir} />
      {/* <Newslatter currentDir={currentDir} /> */}
      <NewsletterSubscribe currentDir={currentDir} />
    </>
  )
}
